### ISSUE TITLE
JVM limits to low in kubernetes deployment file?

### ISSUE THREAD

**Issue by Eneuman** [IHTSDO/snowstorm#279]
Hi again

Maby this is not a problem but when I was setting up snostorm in a Azure Kubernetes cluster, I noticed that the JVM limits in the kubernetes file did not follow the memory guidlines for snowstorm elastic search.

This row
https://github.com/IHTSDO/snowstorm/blob/db5bc85134be59a3ab4234965b95e3e3f63d8904/kubernetes/snowstorm-deploy.yml#L42

seems to limit the memory to just 4 Gb, so event If I set:
```
        resources:
          requests:
            memory: "6Gi"
          limits:
            memory: "8Gi"
```

in my pod, the JVM will only use 4Gb max... or am I missing somthing?
