### ISSUE TITLE
Configurating SSL certificate in docker environment?

### ISSUE THREAD

**Issue by jayped007** [IHTSDO/snowstorm#492]
SUMMARY

Previously to yesterday, our docker-compose.yml for the snowstorm application had the nginx web server, and it had configuration for the SSL certificate we use for this server. 

How would that be configured now?? (since nginx appears to no longer be part of the application).

DETAILS

previous docker-compose.yml service definition for nginx

```
  nginx:
    image: nginx:stable-alpine
    container_name: nginx2
    depends_on:
      - browser
    networks:
      - elastic2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl
      - ./log/nginx:/var/log/nginx
    ports:
      - 443:443
    restart: unless-stopped
```

previous nginx.conf

```
events { }

http {

  map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
  }

  server {
    listen 443 ssl;
    server_name nelexicon.unmc.edu;

    ssl_certificate     /ssl/nelexicon.unmc.edu.cer;
    ssl_certificate_key /ssl/nelexicon.unmc.edu.key;

    access_log /var/log/nginx/data-access.log combined;

    location / {
       proxy_pass http://browser:80/;
       proxy_set_header X-Real-IP  $remote_addr;
       proxy_set_header X-Forwarded-For $remote_addr;
       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_redirect http://snowstorm:80/ $scheme://$http_host/;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection $connection_upgrade;
       proxy_read_timeout 20d;
       proxy_buffering off;
       }
   }
}

```
